export const TaskActionTypes ={
    ADD_TASK : 'ADD_TASK',
    REMOVE_TASK : 'REMOVE_TASK',
    EDIT_TASK : 'EDIT_TASK',
    TASK_COMPLETED : 'TASK_COMPLETED',
    REMOVE_COMPLETED_TASK : 'REMOVE_COMPLETED_TASK'
}